import type { EnrollmentFormData } from "./types"

const nowISO = () => new Date().toISOString()

const buildDerived = (overrides?: Partial<EnrollmentFormData["derived"]>) => ({
  riskFactorScore: 36,
  activityRiskModifier: 0,
  coverageComplexity: "medium" as const,
  ...overrides,
})

export const DEFAULT_ENROLLMENT_FORM: EnrollmentFormData = {
  userId: null,
  fullName: "Sujay Chava",
  preferredName: "Sujay",
  age: null,
  maritalStatus: "single",
  dependents: 0,
  employmentStartDate: "2023-08-01",
  educationLevel: "bachelor",
  educationMajor: "",
  workCountry: "USA",
  workState: "Georgia",
  workRegion: "Southeast",
  coveragePreference: "self",
  homeOwnership: "rent",
  incomeRange: "50-100k",
  healthCoverage: "employer",
  spouseHasSeparateInsurance: null,
  partnerCoverageStatus: "not-applicable",
  savingsRate: 12,
  wantsSavingsSupport: null,
  riskComfort: 3,
  investsInMarkets: null,
  activityLevel: "balanced",
  physicalActivities: false,
  activityList: [],
  tobaccoUse: false,
  disability: false,
  veteran: false,
  creditScore: 680,
  citizenship: "U.S. Citizen",
  residencyStatus: "Citizen",
  hasContinuousCoverage: null,
  hasHealthConditions: null,
  healthConditionSummary: "",
  primaryCareFrequency: "annually",
  prescriptionFrequency: "never",
  activityLevelScore: 3,
  benefitsBudget: 8,
  planPreference: "balanced",
  taxPreferredAccount: "neither",
  anticipatesLifeChanges: null,
  expectedBenefitUsage: "occasionally",
  travelsOutOfState: null,
  needsInternationalCoverage: null,
  dentalVisionPreference: "yes",
  contributesToRetirement: null,
  retirementContributionRate: 6,
  wantsRetirementGuidance: null,
  confidenceInsuranceTerms: 3,
  guidancePreference: "summary",
  createdAt: nowISO(),
  isGuest: false,
  consentToFollowUp: false,
  derived: buildDerived(),
}

export const SAMPLE_COMPLETED_FORM: EnrollmentFormData = {
  ...DEFAULT_ENROLLMENT_FORM,
  userId: "sample-user",
  age: 32,
  maritalStatus: "partnered",
  dependents: 1,
  employmentStartDate: "2021-05-01",
  educationLevel: "master",
  educationMajor: "Finance",
  workCountry: "USA",
  workState: "Pennsylvania",
  workRegion: "Northeast",
  coveragePreference: "self-plus-family",
  homeOwnership: "own",
  incomeRange: "100-200k",
  healthCoverage: "partner",
  spouseHasSeparateInsurance: true,
  partnerCoverageStatus: "yes",
  savingsRate: 18,
  wantsSavingsSupport: false,
  riskComfort: 4,
  investsInMarkets: true,
  activityLevel: "active",
  physicalActivities: true,
  activityList: ["hiking", "gym"],
  tobaccoUse: false,
  disability: false,
  veteran: false,
  creditScore: 720,
  consentToFollowUp: true,
  hasContinuousCoverage: true,
  hasHealthConditions: true,
  healthConditionSummary: "Managed asthma",
  primaryCareFrequency: "several",
  prescriptionFrequency: "occasionally",
  activityLevelScore: 4,
  benefitsBudget: 12,
  planPreference: "lower-deductible",
  taxPreferredAccount: "both",
  anticipatesLifeChanges: false,
  expectedBenefitUsage: "frequently",
  travelsOutOfState: true,
  needsInternationalCoverage: false,
  dentalVisionPreference: "yes",
  contributesToRetirement: true,
  retirementContributionRate: 10,
  wantsRetirementGuidance: true,
  confidenceInsuranceTerms: 4,
  guidancePreference: "step",
  derived: buildDerived({ riskFactorScore: 52, activityRiskModifier: 4 }),
}

export const FORM_STORAGE_KEY = "lifelens-form-cache"
export const INSIGHTS_STORAGE_KEY = "lifelens-insights-cache"
export const MOMENTS_STORAGE_KEY = "lifelens-moments-cache"
export const CHAT_STORAGE_KEY = "lifelens-chat-cache"
export const LEARN_CHAT_STORAGE_KEY = "lifelens-learn-chat-cache"
export const PROFILE_CREATED_KEY = "lifelens-profile-created"
